{
 "title": "DNS Threat Intelligence",
 "tags": [
  "security",
  "pi-hole",
  "n8n"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Domains Scanned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"[YOUR_BUCKET_NAME]\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"domain_threats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"blocked\")\r\n  |> count()\r\n  |> group()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Threats Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"[YOUR_BUCKET_NAME]\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"domain_threats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"blocked\" and (r[\"_value\"] == true or r[\"_value\"] == \"true\"))\r\n  |> group() \r\n  |> count()"
    }
   ]
  },
  {
   "title": "Threat Intelligence Log",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"[YOUR_BUCKET_NAME]\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"domain_threats\")\r\n  |> pivot(rowKey:[\"_time\", \"domain\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> keep(columns: [\"_time\", \"domain\", \"blocked\", \"pulses\", \"vt_detections\"])"
    }
   ]
  }
 ]
}